export const CANGE_SEARCH_FIELD='CANGE_SEARCH_FIELD';
export const REQUEST_ROBOTS_PENDING='REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS='REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILD='REQUEST_ROBOTS_FAILD';